### ISSUE TITLE
Cache latest App Store version and use it when no connection is available

### ISSUE THREAD

**Issue by ilijapuaca** [ArtSabintsev/Harpy#143]
I figured that adding offline support could prove useful, as someone that wants to avoid a force update would simply go offline and get past the check (if applicable).

Caching the last version of the app that was fetched from the App Store (NSUserDefaults would do, just like daily/weekly dates) would allow for the library to show the dialog even when no connection is available by comparing the current version to the one that's cached.

The cached version would be used in two cases:
- No connection available (would probably have to add Reachability for this purpose)
- Request timeout (showing the message after 60 seconds or whatever is probably still better than not showing it at all)

If you think this is worth the hustle, I can help out on the implementation.

**Comment by ArtSabintsev** [comment]
Eh, I'm apprehensive about doing that. 

The whole idea with Harpy is to tell them at launch, rather than interrupt their experience mid-way through their app browsing experience.

I would not want this feature in the master repo, but feel free to roll it on your own branch!

Thanks for the suggestion!

Closing this issue, but feel free to comment, and we can continue the discussion if you'd like.
