### ISSUE TITLE
How about make presentingViewController optional?

### ISSUE THREAD

**Issue by waniwang** [ArtSabintsev/Harpy#145]
Because I've implemented `- (void)harpyDidDetectNewVersionWithoutAlert:(NSString *)message` and I want to use my own custom UI, I think it's not needed to set `presentingViewController`.

How about change the `checkVersion` like following?

``` objective-c
if (!_presentingViewController && self.delegate && ![self.delegate respondsToSelector:@selector(harpyDidDetectNewVersionWithoutAlert:)]) {
    NSLog(@"[Harpy]: Please make sure that you have set _presentationViewController before calling checkVersion, checkVersionDaily, or checkVersionWeekly.");
} else {
    [self performVersionCheck];
}
```

**Comment by ArtSabintsev** [comment]
Ya, this isn't a bad idea. I'll think about it.

Thanks for the suggestion!

**Comment by peseriusz** [comment]
I also think that "launchAppStore" shoud be public, if I have own GUI I want to easy open AppStore

**Comment by ArtSabintsev** [comment]
Sure, that makes sense. I'll do both of these when I get some time.

**Comment by slxl** [comment]
Hi, Arthur! 
Another way is to discard it completely and use just a dedicated UIWindow for that placed on top. Any cons in that?

I just had a project now where root view controller is being changed few times during launch and at the moment when app AppStore version is retrieved - assigned root vc could not exist anymore.

**Comment by ArtSabintsev** [comment]
I haven't forgotten about this stuff, just been busy. I'll take another look soon.

**Comment by ArtSabintsev** [comment]
@slxl In your situation, I would wait until all the rootVC switching is done before calling Harpy's version checking methods.

**Comment by ArtSabintsev** [comment]
While I see the virtue of implementing this feature, I have decided against it for two specific reasons.

First, the majority of users will not be using the `harpyDidDetectNewVersionWithoutAlert:` delegate method. Therefore, when implementing this feature, I'll have to remove the following error log in the  `checkVersion` method.

```objc
NSLog(@"[Harpy]: Please make sure that you have set` _presentationViewController` before calling checkVersion, checkVersionDaily, or checkVersionWeekly.");
``` 

I added this error log because people don't RTFM, and therefore, didn't set `_presentationViewController` and complained to me that Harpy wasn't working. For me, I need to support what makes sense from the new-developer-integration perspective, so I have opted to keep the existing logic.

The second reason is that some people, albeit even fewer than those of you that use `harpyDidDetectNewVersionWithoutAlert`, will want to make use of both options ; having Harpy presenting the UIAlertController _**and**_ do something else within when the delegate method is called. I can think of many reasons why people would want to do this, but I don't know many who have actually implemented Harpy in this manner.

This second reason is why the implementation of the following functions isn't `if-else` but rather `if` followed by another `if`.

```objc
- (void)showAlertController:(UIAlertController *)alertController {

    if (_presentingViewController != nil) {
        [_presentingViewController presentViewController:alertController animated:YES completion:nil];

        if (_alertControllerTintColor) {
            [alertController.view setTintColor:_alertControllerTintColor];
        }
    }

    if ([self.delegate respondsToSelector:@selector(harpyDidShowUpdateDialog)]){
        [self.delegate harpyDidShowUpdateDialog];
    }
}
```

I hope my explanation makes sense. I'm sorry for making you all wait so long. I just had to think about this for a good long while.

Closing this ticket, but feel free to comment as I will happily continue the discussion.
